#!/usr/bin/env bash
# install_ubuntu.sh — Install pySTXPlanePanels on Ubuntu (PC / x86-64)
#
# Run as your normal user (not root). sudo is used only for apt.
# Tested against Ubuntu 22.04 LTS and 24.04 LTS.

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
REPO_URL="https://github.com/leleopard/pySTXPlanePanels.git"
INSTALL_DIR="$HOME/plane_gauges"
VENV_DIR="$INSTALL_DIR/.venv"
BIN="$VENV_DIR/bin"

# ── Colours ───────────────────────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; N='\033[0m'
ok()      { echo -e "${G}  ✓  ${N}$*"; }
warn()    { echo -e "${Y}  !  ${N}$*"; }
err()     { echo -e "${R}  ✗  ${N}$*" >&2; }
section() { echo -e "\n${B}━━━  $*  ━━━${N}"; }

ask_yn() {   # ask_yn "Question" → returns 0=yes 1=no
    local answer
    while true; do
        read -rp "    $1 [y/n]: " answer
        case "$answer" in
            [Yy]) return 0 ;;
            [Nn]) return 1 ;;
            *)    echo "      Please enter y or n." ;;
        esac
    done
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${B}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║   pySTXPlanePanels — Ubuntu PC Setup     ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${N}"

# ── 1. Python version check ───────────────────────────────────────────────────
section "Python"
PY=$(command -v python3 || true)
if [ -z "$PY" ]; then
    err "python3 not found. Install it with:  sudo apt install python3"
    exit 1
fi
PY_VER=$("$PY" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=${PY_VER%%.*}
PY_MINOR=${PY_VER#*.}
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 10 ]; }; then
    err "Python 3.10+ required, found $PY_VER."
    err "Ubuntu 22.04 ships Python 3.10, Ubuntu 24.04 ships Python 3.12."
    exit 1
fi
ok "Python $PY_VER"

# ── 2. System packages ────────────────────────────────────────────────────────
section "System packages"
PKGS=()
for pkg in python3-venv python3-pip git; do
    dpkg -s "$pkg" &>/dev/null || PKGS+=("$pkg")
done
if [ ${#PKGS[@]} -gt 0 ]; then
    echo "  Installing: ${PKGS[*]}"
    sudo apt-get install -y "${PKGS[@]}"
fi
ok "System packages ready"

# ── 3. Clone / update repo ────────────────────────────────────────────────────
section "Repository"
if [ -d "$INSTALL_DIR/.git" ]; then
    ok "Repo already at $INSTALL_DIR — pulling latest"
    git -C "$INSTALL_DIR" pull --ff-only
else
    echo "  Cloning into $INSTALL_DIR ..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    ok "Cloned"
fi

# ── 4. Virtual environment ────────────────────────────────────────────────────
section "Virtual environment"
if [ ! -d "$VENV_DIR" ]; then
    echo "  Creating venv at $VENV_DIR ..."
    "$PY" -m venv "$VENV_DIR"
fi
ok "Venv ready"
PIP="$BIN/pip"
"$PIP" install --upgrade pip --quiet

# ── 5. Core dependencies ──────────────────────────────────────────────────────
section "Core dependencies"
echo "  Installing arcade, pyyaml, pillow, pyxpudpserver ..."
echo "  (arcade is ~100 MB; first install may take a minute)"
"$PIP" install \
    "arcade>=3.3,<4" \
    "pyyaml>=6.0" \
    "pillow>=10.0" \
    "pyxpudpserver" \
    --quiet
ok "Core dependencies installed"

# ── 6. Install this package ───────────────────────────────────────────────────
section "gauge_core"
echo "  Installing pySTXPlanePanels in editable mode ..."
"$PIP" install -e "$INSTALL_DIR" --quiet
ok "gauge_core installed"

# ── 7. Optional: gauge_designer (PySide6) ────────────────────────────────────
section "Optional: gauge_designer"
warn "PySide6 is ~700 MB. Only needed if you want the WYSIWYG editor."
INSTALL_DESIGNER=false
if ask_yn "Install gauge_designer (PySide6)?"; then
    echo "  Installing PySide6 ..."
    "$PIP" install "PySide6>=6.5" --quiet
    DESIGNER_LAUNCHER="$INSTALL_DIR/start_designer.sh"
    cat > "$DESIGNER_LAUNCHER" <<DESIGNER_EOF
#!/usr/bin/env bash
# Auto-generated by install_ubuntu.sh
cd "$INSTALL_DIR"
exec "$BIN/gauge-designer" "\$@"
DESIGNER_EOF
    chmod +x "$DESIGNER_LAUNCHER"
    ok "gauge_designer available — launcher: $DESIGNER_LAUNCHER"
    INSTALL_DESIGNER=true
else
    ok "Skipped — install later with:  $PIP install 'PySide6>=6.5'"
fi

# ── 7b. Add venv bin to PATH ──────────────────────────────────────────────────
section "Shell PATH"
BASHRC="$HOME/.bashrc"
PATH_MARKER="# pySTXPlanePanels venv"
if grep -qF "$PATH_MARKER" "$BASHRC" 2>/dev/null; then
    ok "PATH already configured in $BASHRC"
else
    {
        echo ""
        echo "$PATH_MARKER"
        echo "export PATH=\"$VENV_DIR/bin:\$PATH\""
    } >> "$BASHRC"
    ok "Added venv bin to PATH in $BASHRC"
    warn "Run 'source ~/.bashrc' or open a new terminal for bare commands."
fi

# ── 8. UDP config ─────────────────────────────────────────────────────────────
section "UDP / X-Plane network config"
CONFIG_FILE="$INSTALL_DIR/config.yaml"
echo "  Current config ($CONFIG_FILE):"
echo "  ─────────────────────────────────────────"
sed 's/^/    /' "$CONFIG_FILE"
echo "  ─────────────────────────────────────────"
warn "Edit $CONFIG_FILE to set xplane_host to your X-Plane PC's IP address."
warn "Set listen_host to 0.0.0.0 if X-Plane is on a different machine."

# ── 9. Choose default panel ───────────────────────────────────────────────────
section "Default panel"
echo "  Available panels:"
PANELS=()
i=1
while IFS= read -r -d '' f; do
    rel="${f#$INSTALL_DIR/}"
    echo "    $i) $rel"
    PANELS+=("$f")
    ((i++))
done < <(find "$INSTALL_DIR/panels" -name "*.yaml" -print0 | sort -z)

DEFAULT_PANEL="${PANELS[0]}"
read -rp "    Pick a panel number [1]: " PANEL_CHOICE
PANEL_CHOICE="${PANEL_CHOICE:-1}"
if [[ "$PANEL_CHOICE" =~ ^[0-9]+$ ]] && [ "$PANEL_CHOICE" -ge 1 ] && [ "$PANEL_CHOICE" -le "${#PANELS[@]}" ]; then
    DEFAULT_PANEL="${PANELS[$((PANEL_CHOICE - 1))]}"
fi
ok "Default panel: ${DEFAULT_PANEL#$INSTALL_DIR/}"

# ── 10. Launcher script ───────────────────────────────────────────────────────
LAUNCHER="$INSTALL_DIR/start_panel.sh"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by install_ubuntu.sh
# Edit PANEL and SSAA to taste.
PANEL="${DEFAULT_PANEL#$INSTALL_DIR/}"
SSAA=4   # Anti-aliasing: 0=off  2=light  4=default  8=heavy

cd "$INSTALL_DIR"
exec "$BIN/plane-gauge" "\$PANEL" --ssaa "\$SSAA"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
ok "Launcher written: $LAUNCHER"

# ── 11. Optional: desktop shortcut ───────────────────────────────────────────
section "Desktop shortcut"
DESKTOP_FILE="$HOME/Desktop/PlaneGauges.desktop"
if ask_yn "Create a desktop shortcut for the panel?"; then
    mkdir -p "$HOME/Desktop"
    cat > "$DESKTOP_FILE" <<DESKFILE_EOF
[Desktop Entry]
Name=Plane Gauges
Comment=X-Plane gauge panel
Exec=$LAUNCHER
Terminal=false
Type=Application
Icon=utilities-terminal
DESKFILE_EOF
    chmod +x "$DESKTOP_FILE"
    ok "Desktop shortcut created: $DESKTOP_FILE"
fi

if [ "$INSTALL_DESIGNER" = true ]; then
    DESIGNER_DESKTOP="$HOME/Desktop/PlaneGaugesDesigner.desktop"
    if ask_yn "Create a desktop shortcut for the gauge designer?"; then
        cat > "$DESIGNER_DESKTOP" <<DESKFILE2_EOF
[Desktop Entry]
Name=Plane Gauges Designer
Comment=WYSIWYG instrument/panel editor
Exec=$DESIGNER_LAUNCHER
Terminal=false
Type=Application
Icon=applications-graphics
DESKFILE2_EOF
        chmod +x "$DESIGNER_DESKTOP"
        ok "Designer shortcut created: $DESIGNER_DESKTOP"
    fi
fi

# ── 12. Optional: autostart on login ─────────────────────────────────────────
section "Autostart on login"
AUTOSTART_FILE="$HOME/.config/autostart/plane_gauges.desktop"
if ask_yn "Auto-start the panel when the desktop logs in?"; then
    mkdir -p "$HOME/.config/autostart"
    cat > "$AUTOSTART_FILE" <<AUTOSTART_EOF
[Desktop Entry]
Name=Plane Gauges
Comment=X-Plane gauge panel
Exec=$LAUNCHER
Type=Application
X-GNOME-Autostart-enabled=true
AUTOSTART_EOF
    ok "Autostart entry created: $AUTOSTART_FILE"
    warn "The panel will launch automatically on next desktop login."
    warn "To disable: rm $AUTOSTART_FILE"
else
    ok "Skipped — start manually with:  $LAUNCHER"
fi

# ── 13. Summary ───────────────────────────────────────────────────────────────
section "Done"
echo ""
echo "  Installation complete. Quick reference:"
echo ""
echo "  Run panel:       $LAUNCHER"
echo "  Run panel (cmd): plane-gauge <panel.yaml>          (new terminal)"
echo "  Test mode:       plane-gauge <panel.yaml> --test"
if [ "$INSTALL_DESIGNER" = true ]; then
echo "  Designer:        $DESIGNER_LAUNCHER"
echo "  Designer (cmd):  gauge-designer                    (new terminal)"
fi
echo "  UDP config:      $CONFIG_FILE"
echo "  Update repo:     git -C $INSTALL_DIR pull"
echo ""
warn "Open a new terminal (or run 'source ~/.bashrc') before using bare commands."
echo ""
warn "Remember to set xplane_host in config.yaml to your X-Plane PC's IP."
echo ""
